import {
  Zap, Users, MessageSquare, BarChart3, FlaskConical, Route,
  Bell, Search, Settings, Sparkles, ArrowUp, ArrowDown,
  ArrowUpRight, ArrowDownRight, AlertTriangle, CheckCircle2,
  Clock, Circle, ChevronLeft, ChevronRight, ChevronDown, MoreHorizontal, PanelLeftClose, PanelLeftOpen, Menu,
  Send, Mic, Phone, FileText, Heart, Shield, Receipt,
  Calendar, Plus, X, Filter, Download, RefreshCw, GitBranch,
  Pause, Play, LogOut, User, Loader2, ThumbsUp, ThumbsDown,
  GripVertical, LayoutDashboard, SlidersHorizontal, Stethoscope,
  TestTube2, Pill, Activity, UserCheck, Home, ClipboardCheck,
  ShieldX, ArrowRightLeft, ClipboardList, UserPlus, AlertCircle,
  Calculator, TrendingUp, TrendingDown, ExternalLink, ShieldCheck,
  Eye, Rocket, Save,
  type LucideIcon,
} from "lucide-react";

export const Icons = {
  commandCenter: Zap,
  patients: Users,
  communications: MessageSquare,
  outcomes: BarChart3,
  cohortisation: FlaskConical,
  pathwayBuilder: Route,
  notifications: Bell,
  search: Search,
  settings: Settings,
  ai: Sparkles,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  uptier: ArrowUpRight,
  downtier: ArrowDownRight,
  warning: AlertTriangle,
  completed: CheckCircle2,
  pending: Clock,
  idle: Circle,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  more: MoreHorizontal,
  menu: Menu,
  panelClose: PanelLeftClose,
  panelOpen: PanelLeftOpen,
  send: Send,
  mic: Mic,
  phone: Phone,
  documents: FileText,
  health: Heart,
  risk: Shield,
  claims: Receipt,
  calendar: Calendar,
  add: Plus,
  close: X,
  filter: Filter,
  download: Download,
  recurring: RefreshCw,
  conditional: GitBranch,
  paused: Pause,
  active: Play,
  logout: LogOut,
  user: User,
  spinner: Loader2,
  thumbsUp: ThumbsUp,
  thumbsDown: ThumbsDown,
  // Pathway builder icons
  plus: Plus,
  drag: GripVertical,
  canvas: LayoutDashboard,
  config: SlidersHorizontal,
  diagnosis: Stethoscope,
  lab: TestTube2,
  pharmacy: Pill,
  utilisation: Activity,
  demographics: UserCheck,
  sdoh: Home,
  pro: ClipboardCheck,
  exclusion: ShieldX,
  outreach: MessageSquare,
  referral: ArrowRightLeft,
  medication: Pill,
  assessment: ClipboardList,
  careTeam: UserPlus,
  wait: Clock,
  missingData: AlertCircle,
  compositeScore: Calculator,
  trendUp: TrendingUp,
  trendDown: TrendingDown,
  external: ExternalLink,
  override: ShieldCheck,
  schedule: Calendar,
  preview: Eye,
  publish: Rocket,
  saveDraft: Save,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof Icons;
