import {
  Zap, Users, MessageSquare, BarChart3, FlaskConical, Route,
  Bell, Search, Settings, Sparkles, ArrowUp, ArrowDown,
  ArrowUpRight, ArrowDownRight, AlertTriangle, CheckCircle2,
  Clock, Circle, ChevronRight, ChevronDown, MoreHorizontal,
  Send, Mic, Phone, FileText, Heart, Shield, Receipt,
  Calendar, Plus, X, Filter, Download, RefreshCw, GitBranch,
  Pause, Play, LogOut, User, Loader2, ThumbsUp, ThumbsDown,
  type LucideIcon,
} from "lucide-react";

export const Icons = {
  commandCenter: Zap,
  patients: Users,
  communications: MessageSquare,
  outcomes: BarChart3,
  cohortisation: FlaskConical,
  pathwayBuilder: Route,
  notifications: Bell,
  search: Search,
  settings: Settings,
  ai: Sparkles,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  uptier: ArrowUpRight,
  downtier: ArrowDownRight,
  warning: AlertTriangle,
  completed: CheckCircle2,
  pending: Clock,
  idle: Circle,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  more: MoreHorizontal,
  send: Send,
  mic: Mic,
  phone: Phone,
  documents: FileText,
  health: Heart,
  risk: Shield,
  claims: Receipt,
  calendar: Calendar,
  add: Plus,
  close: X,
  filter: Filter,
  download: Download,
  recurring: RefreshCw,
  conditional: GitBranch,
  paused: Pause,
  active: Play,
  logout: LogOut,
  user: User,
  spinner: Loader2,
  thumbsUp: ThumbsUp,
  thumbsDown: ThumbsDown,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof Icons;
